### ISSUE TITLE
Make @Eternal Diaronlapiredcoalgold rainbow

### ISSUE THREAD

**Issue by Awakened-Redstone** [Bobby-McBobface/phnix-discord-bot#22]
- [ ] Change role color up to 10 times per second, to keep below discord rate limit
- [ ] Reduce color changes on feed message, commands and level up, to avoid reaching rate limit fast
- [ ] Make pull request
- [ ] Get some free time to work on it, somehow

**Comment by Bobby-McBobface** [comment]
No, we are not adding that.
